### ISSUE TITLE
iOS deployment target

### ISSUE THREAD

**Issue by denkeni** [Ptt-official-app/Ptt-iOS#44]
Based on previous internal anonymous developer survey (2021-04), there were 2 out of 3 felt constrained with iOS 9 deployment target requirement. Also referencing another [iOS Developer Community Survey 2020](https://iosdevsurvey.com/2020/04-development/#q30), so the deployment requirement was [updated to iOS 14](https://github.com/Ptt-official-app/Ptt-iOS/commit/4749790a7221b24a6e6307f90cc6a595b546541b).

I also proposed to keep the old compatibility code for a while, in order to respond to iOS backward compatibility requests from users, if there’s any, after the app is public on the App Store ([internal discussion ref](https://t.me/c/1400788359/297)).

Some people argued users on Ptt are more “geeky” and thus more willing to update to the latest OS version. I would doubt the speculation, and hope the official app would be able to target at broader audience. 

[As measured by the App Store on June 3, 2021](https://developer.apple.com/support/app-store/), there were 15% of all devices use iOS 13 or earlier, and 21% of all devices use iPadOS 13 or earlier. Since Apple has continued to [support iOS 14 for important security updates](https://www.apple.com/ios/ios-15/features/), the market share ratio may not change much after iOS 15 release.

The official app also competes with other 3rd party Ptt apps, for minimum iOS version support:
- iOS 9: JPTT, MeowPtt
- iOS 10: PiTT, PTT+, nPTT
- iOS 11: BePTT
- iOS 12: Mo PTT, 鄉民愛 COWBA

This issue would be open for comments from the community, and for revisiting when necessary.

**Comment by denkeni** [comment]
Time flies. Apple just updated with latest data. [As measured by devices that transacted on the App Store on February 14, 2023](https://developer.apple.com/support/app-store/), there were 28% of all devices use iOS 15 or earlier, and 50% of all devices use iPadOS 15 or earlier.

For other 3rd party Ptt apps, minimum iOS version:
- iOS 9: PTT喵
- iOS 10: PTT+, PttX
- iOS 11: nPTT, PUTYPUTY, Ptt2u
- iOS 12: JPTT, BePTT, Mo PTT
- iOS 13: PiTT, 鄉民愛COWBA
- iOS 14: Ptter

As of 23 Jan 2023, Apple has continued to support iOS 12, 15 and the latest iOS 16. (source: [Apple security updates](https://support.apple.com/en-us/HT201222))

Lastly, while [Xcode 13](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes) supports on-device debugging for iOS 9 and later, [Xcode 14](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes) supports on-device debugging in iOS 11 and later. Xcode 14.1 will be required for App Store submissions, starting April 2023. (source: [Apple Developer News and Updates](https://developer.apple.com/news/))

**Comment by xxi511** [comment]
> there were 28% of all devices use iOS 15 or earlier.   

Well...  it is 20% of iOS 15 and 8% of earlier.   
20% is a huge number, it is make sense to support iOS 15 or iOS 14 (by now).   

But about earlier version.... can we drop them?     
So we can use `SwiftUI`.  
When can we have decision?

**Comment by denkeni** [comment]
The deployment requirement has been iOS 14 so SwiftUI can be used, for quite some time.
If you’re keen to drop support for iOS 13 or earlier, please update #43 so it can be merged.

**Comment by xxi511** [comment]
ok, I asked because you said `hope the official app would be able to target at broader audience.`. 
If this is not the case nowadays  
That is great!   

Then I would like to raise another discussion.  
Don't use `Texture` to develop new things.  

If the deployment target is iOS 14, `SwiftUI` will be another strong option.  
Then this project has 3 layout styles, `Texture`, `UIKit` based, and `SwiftUI`.  
I have to say this increases learning curve    

* UIKit: classic, every iOS developer should familiar it 
* SwiftUI: new but native, more and more developers use it, some (e.g. me) haven't had a chance to use it but I think most developers will familiarize it in someday 
* Texture: tldr, I don't see benefit from this library 

I admit I don't have enough knowledge of this library, but from my understanding, this library provides better performance. But seriously, is PTT complex enough that we need to rely on this library to improve performance? 
Second, I am not sure how many developer use `Texture`, this increases learning curve.   
Last, `Texture` is not active, we all know iOS/ Xcode update could break something, what if it breaks one day and no one fix it (e.g. Unit test issue we had), ~~it works don't upgrade~~ 😛

**Comment by denkeni** [comment]
As for Texture, that'll be another issue. Please see #59.

**Comment by xxi511** [comment]
Nice, I think this issue can be closed?
